### ISSUE TITLE
Version 1.1.0 Breaks Image Functionality

### ISSUE THREAD

**Issue by msyhr** [staempfli/magento2-module-widget-extra-fields#11]
After a composer update, the codebase was updated to v 1.1.0 (from 1.0.2) this breaks the image upload functionality and reverts the image links to the "directive" styled cms wysiwyg links. Manually installing the 1.0.2 and removing the composer lib fixes the issue. 

![Screenshot from 2019-03-11 14-23-59](https://user-images.githubusercontent.com/22968596/54151864-cf9bcf00-4409-11e9-917d-ae804e90ac45.png)

**Comment by audef1** [comment]
Version 1.1 was removed, it was rushed out too soon.
