### ISSUE TITLE
How to add WYSIWYG field

### ISSUE THREAD

**Issue by rossmc** [staempfli/magento2-module-widget-extra-fields#4]
Have you added functionality to add WYSIWYG fields?  I can't see from code or readme how to add a WYSIWYG filed.

Image uploader works very nicely, thanks 👍

**Comment by jalogut** [comment]
Hi @rossmc 
That was also our idea at first. We also wanted to add WYSIWYG fields. We tried but we faced several issues that made it not possible. We also realised that having WYSIWYG fileds inside a WYSIWYG field is not the right approach. If you need to add formatted content inside the original WYSIWYG, you should create custom TinyMCE plugins. You can see how we did it here:
- https://blog.hauri.me/how-to-add-a-tinymce-plugin-to-the-magento2-wysiwyg-editor.html

**Comment by rossmc** [comment]
Thanks, that makes sense.  I was thinking myself that it's better in a way for users to just add text and not have to be concerned about the html WYSIWYG adds.

By the way,  I created a small ui-card widget which uses this extension.  Thanks 👍 
https://github.com/rossmc/CardWidget
